/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


/**
 *
 * @author Toshiba-PC
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
//        add(panelGame);
//        add(panelDesign);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        labelClick = new javax.swing.JLabel();
        buttonClick = new javax.swing.JButton();
        labelSuggestion = new javax.swing.JLabel();
        panelSuggestion = new javax.swing.JPanel();
        labelGame = new javax.swing.JLabel();
        labelDesign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(300,800);

        container.setBackground(new java.awt.Color(121, 134, 203));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 81, 181), 3));

        labelClick.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        labelClick.setForeground(new java.awt.Color(197, 202, 233));
        labelClick.setText("Click Here !");
        labelClick.setSize(100,30);
        //labelClick.setLocationRelativeTo(null);

        buttonClick.setBackground(new java.awt.Color(197, 202, 233));
        buttonClick.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        buttonClick.setText("GET");
        buttonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClickActionPerformed(evt);
            }
        });
        buttonClick.setSize(100,50);
        //buttonClick.setLocationRelativeTo(null);

        labelSuggestion.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        labelSuggestion.setForeground(new java.awt.Color(197, 202, 233));
        labelSuggestion.setText("Suggestion :");

        panelSuggestion.setBackground(new java.awt.Color(197, 202, 233));
        //panelSuggestion.setLocationRelativeTo(null);

        labelGame.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        labelGame.setForeground(new java.awt.Color(121, 134, 203));
        labelGame.setText("You got 1 hour of gaming");
        labelGame.setVisible(false);

        labelDesign.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        labelDesign.setForeground(new java.awt.Color(121, 134, 203));
        labelDesign.setText("You got 1 hour of designing");
        labelDesign.setVisible(false);

        javax.swing.GroupLayout panelSuggestionLayout = new javax.swing.GroupLayout(panelSuggestion);
        panelSuggestion.setLayout(panelSuggestionLayout);
        panelSuggestionLayout.setHorizontalGroup(
            panelSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSuggestionLayout.createSequentialGroup()
                    .addGap(0, 73, Short.MAX_VALUE)
                    .addComponent(labelGame)
                    .addGap(0, 74, Short.MAX_VALUE)))
            .addGroup(panelSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSuggestionLayout.createSequentialGroup()
                    .addGap(0, 68, Short.MAX_VALUE)
                    .addComponent(labelDesign)
                    .addGap(0, 68, Short.MAX_VALUE)))
        );
        panelSuggestionLayout.setVerticalGroup(
            panelSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(panelSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSuggestionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelGame)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSuggestionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelDesign)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelClick)
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(buttonClick))))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelSuggestion)))
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelSuggestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelClick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClick)
                .addGap(12, 12, 12)
                .addComponent(labelSuggestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSuggestion.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    double temp;
    boolean clicked = false;
    
    private void buttonClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClickActionPerformed
        // TODO add your handling code here:
        temp = Math.random();
        if (clicked) {
            labelGame.setVisible(false);
            labelDesign.setVisible(false);
        }
        if (temp < 0.5) { 
            labelGame.setVisible(true);
        }
        else {
            labelDesign.setVisible(true);
        }
        clicked = true;
    }//GEN-LAST:event_buttonClickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClick;
    private javax.swing.JPanel container;
    private javax.swing.JLabel labelClick;
    private javax.swing.JLabel labelDesign;
    private javax.swing.JLabel labelGame;
    private javax.swing.JLabel labelSuggestion;
    private javax.swing.JPanel panelSuggestion;
    // End of variables declaration//GEN-END:variables
    
}